apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLables:
      app: nginx-app
  template:
    metadata:
      lables:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: pardeeparora/custom-nginx-k8s
        ports:
          containerPort: 80