apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-dev
  labels:
    app: nginx-app-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-app-dev
  template:
    metadata:
      labels:
        app: nginx-app-dev
    spec:
      containers:
      - name: nginx-app-dev
        image: pardeeparora/custom-nginx-k8s
        ports:
        - containerPort: 80