apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:  # ✅ fixed spelling
      app: nginx-app
  template:
    metadata:
      labels:  # ✅ fixed spelling
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: pardeeparora/custom-nginx-k8s
        ports:
        - containerPort: 80