apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  lables:
    app: nginx-app
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30787