apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc-dev
  lables:
    app: nginx-app-dev
spec:
  type: NodePort
  selector:
    app: nginx-app-dev
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30788