apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-prod
  labels:
    app: nginx-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-prod
  template:
    metadata:
      labels:
        app: nginx-app-prod
    spec:
      containers:
      - name: nginx-app-prod
        image: pardeeparora/custom-nginx-k8s
        ports:
        - containerPort: 80